### ISSUE TITLE
enforce docker-compose version

### ISSUE THREAD

**Issue by philipp-zettl** [philsupertramp/docr#1]
I've noticed issues when running with outdated `docker-compose` (`==1.29.2`).
Please build version constraints to fix the `docker-compose` version.

This should fix:
- `compose_` vs. `compose-` naming
- `--no-ansi` vs `--ansi no`

**Comment by romanmeister** [comment]
[name.txt](https://github.com/philsupertramp/docr/files/10482296/name.txt)

**Comment by philsupertramp** [comment]
Cheers for the working diff!!

I looked into the docker-compose version I'm running on my private machine.

```shell
> docker-compose --version
Docker Compose version 2.14.2
```

**Comment by philsupertramp** [comment]
Fixing:
- `^1.29.0`: 
  - `compose_${CONTAINER_NAME}`
- `^2.14.0`:
  - `compose-${CONTAINER_NAME}`

Seems like we can use the same option when referring to the ansi output:
- `--ansi never`
